### ISSUE TITLE
mac-rewrite.sh use of lxc-ls produces no output

### ISSUE THREAD

**Issue by vmorris** [ubuntu-openstack/zopenstack#10]
I have lxc-ls installed, but it doesn't produce any output! Should the mac-rewrite.sh be rewritten to use `lxc list` instead?

> ubuntu@zp93kv8:~$ sudo lxc-ls

> ubuntu@zp93kv8:~$ lxc-ls --version
> 2.0.6

> ubuntu@zp93kv8:~$ which lxc-ls
> /usr/bin/lxc-ls

> ubuntu@zp93kv8:~$ sudo lxc list
> +---------------------+---------+-------------------+------+------------+-----------+
> |        NAME         |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
> +---------------------+---------+-------------------+------+------------+-----------+
> | juju-f67327-0-lxd-0 | RUNNING | 10.0.0.223 (eth0) |      | PERSISTENT | 0         |
> +---------------------+---------+-------------------+------+------------+-----------+

> ubuntu@zp93kv8:~$ cat /etc/os-release 
> NAME="Ubuntu"
> VERSION="16.04.1 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.1 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

**Comment by ryan-beisner** [comment]
The reference docs currently in the repo were exercised with Juju 1.x, which installs lxc and lxc-ls.  With Juju 2.x, lxd is installed, which uses the lxc command and not lxc-ls.  We plan to revise the docs to reflect the procedure with Juju 2.x now that it is released.

**Comment by vmorris** [comment]
Thanks @ryan-beisner.
