### ISSUE TITLE
Unable to deploy bundle-mitaka-s390x.yaml

### ISSUE THREAD

**Issue by vmorris** [ubuntu-openstack/zopenstack#18]
It seems ceph-radosgw has removed an option:

ubuntu@zs93kvi:~/openstack-on-lxd$ juju deploy bundle-mitaka-s390x.yaml
Deploying charm "cs:ceph-271"
reusing application ceph (charm: cs:ceph-271)
configuration updated for application ceph
Deploying charm "cs:ceph-radosgw-247"
ERROR cannot deploy bundle: cannot deploy application "ceph-radosgw": unknown option "use-embedded-webserver"

I removed the option from the config and it does at least deploy. I have not yet determined if it's functional.

**Comment by AurelienLourot** [comment]
This seems to have been fixed meanwhile in `master`, closing. Let us know if this is still an issue, thanks!
