### ISSUE TITLE
Tempest installation

### ISSUE THREAD

**Issue by liwbj** [ubuntu-openstack/zopenstack#8]
@ryan-beisner Hi I read your code  about zopenstack/tools/2-configure/profiles/s390x-multi-lpar

And found you are trying to install tempest as below, but I found you just download and update the conf file without pip installation. Not sure if it is missed or just works as your design?

>  Git tempest, place the rendered tempest template
[ -d tempest ] || git clone https://github.com/openstack/tempest
cp tempest.conf tempest/etc#

Here is the doc of tempest, it needs pip install tempest/
https://github.com/openstack/tempest

**Comment by vmorris** [comment]
I had noticed this as well @liwbj. My thought was that it is WIP, and not actually implemented yet.

**Comment by ryan-beisner** [comment]
That is correct.  Tempest usage in this context is not yet documented here.  The presence of that profile config is by mistake.  We'll update the repo accordingly.  Thank you.
