### ISSUE TITLE
Is Juju 1.25 a requirement?

### ISSUE THREAD

**Issue by vmorris** [ubuntu-openstack/zopenstack#9]
I attempted to deploy a custom bundle that's not too dissimilar from the one listed herein, but I'm using Juju 2. Should this be possible, or do I need to be on 1.25 to do a bundle deploy to manually added machines?

> $ juju version
> 2.0.2-xenial-s390x
> 
> $ juju status
> << snip >>
> Machine  State    DNS       Inst id           Series  AZ
> 0        started  REDACTED  manual:REDACTED   xenial
> 1        started  REDACTED  manual:REDACTED   xenial
> 2        started  REDACTED  manual:REDACTED   xenial
> << snip >>

When I go to deploy a bundle that defines machines 0, 1, and 2 and describes deployment of services to these machines, the charms are deployed, but no units are created.

> ERROR cannot deploy bundle: cannot create machine for holding aodh, ceilometer, ceph-mon, ceph-osd, cinder, glance, keystone, mongodb, mysql, neutron-api, neutron-gateway, nova-cloud-controller, nova-compute, openstack-dashboard, rabbitmq-server, swift-proxy and swift-storage-z1 units: cannot add a new machine: use "juju add-machine ssh:[user@]<host>" to provision machines

If I manually deploy charms to the manually added machines, it's happy to oblige.

According to the following, I wonder if I'm out in uncharted territory here.
https://github.com/ubuntu-openstack/zopenstack/blob/master/bundles/lpar/xenial-mitaka-stable.yaml#L11

**Comment by ryan-beisner** [comment]
When using a bundle that needs to re-use or place units on existing or manual machines, the juju-deployer tool must be used currently.

The `juju-deployer` tool has more mature features regarding machine placement than the newer native `juju deploy` command.  Juju-deployer has been updated to work with both 1.25.x and 2.x.
